"""Notification timestamp type

Revision ID: e57560f6e507
Revises: 4c651e12ecdd
Create Date: 2020-07-25 14:27:26.981181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e57560f6e507'
down_revision = '4c651e12ecdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notification', 'timestamp',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notification', 'timestamp',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=True)
    # ### end Alembic commands ###
